github:
  prebuilds:
    pullRequestsFromForks: true
    addComment: true
    
image:
  file: .gitpod.Dockerfile

# tasks:
#   - before: curl https://raw.githubusercontent.com/aws/aws-cdk/master/package.json -o package.json
#     init:  yarn install

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.5:9Wg0Glx/TwD8ElFBg+FKcQ==